MODULE ERRORESTIMATE

	USE NEWTYPE
	USE GLBVAR
	USE EXACTSOL
	USE PACKAGE
	USE LOADFUNCTION

    IMPLICIT NONE
    
CONTAINS

!----MAX. NORM ESTIMATE----
SUBROUTINE MAXNORM(COEFF_APDISP)

	REAL*8, INTENT(IN) :: COEFF_APDISP(3*DOF)
	TYPE(POINT2D) :: MESH
	INTEGER :: II, I, J, NDX(3,DOF), INDICE(6), NGRID, MAXGRID(2)
	TYPE(DISPLACEMENT), ALLOCATABLE :: EXDISP(:), APDISP(:), ERROR_DISP(:)
	TYPE(MOMENT), ALLOCATABLE :: EXMOMENT(:), APMOMENT(:), ERROR_MOMENT(:)
	TYPE(STRESS), ALLOCATABLE :: EXSTRESS(:)
	REAL*8, ALLOCATABLE :: XCORDS(:), YCORDS(:)
	REAL*8 :: EX_W_BAR_CENTER, EX_W_HAT, AP_W_BAR_CENTER, AP_W_HAT
	TYPE(STRESS) :: STRESS_BAR
	
    CALL STIFINDEX(NDX)
    
	MAXGRID = (99,99)
	
	ALLOCATE(XCORDS(MAXGRID(1)+1), YCORDS(MAXGRID(2)+1))
	NGRID = UBOUND(XCORDS,1)*UBOUND(YCORDS,1)

	ALLOCATE(ERROR_DISP(NGRID), EXMOMENT(NGRID))
	ALLOCATE(EXDISP(NGRID), APDISP(NGRID), APMOMENT(NGRID))
	ALLOCATE(EXSTRESS(NGRID), ERROR_MOMENT(NGRID))
		
	MESH=POINT2D((OMEGA%PT2%X-OMEGA%PT1%X)/MAXGRID(1), (OMEGA%PT4%Y-OMEGA%PT1%Y)/MAXGRID(2))
	
	DO II=1, MAXGRID(1)+1
		XCORDS(II)=OMEGA%PT1%X+MESH%X*(II-1)
	ENDDO
	
	DO II=1, MAXGRID(2)+1
		YCORDS(II)=OMEGA%PT1%Y+MESH%Y*(II-1)
	ENDDO

	!----- COMPUTE FOURIER SERIES OF ANALYTIC SOLUTION -----
	CALL NAVIERSOL(EXDISP, EXMOMENT, EXSTRESS, XCORDS, YCORDS, 29, 29)

	!----- COMPUTE ANALYTIC NONDIMENSIONAL NUMERICAL RESULT -----
	CALL EXNONDIMRESULT(EX_W_BAR_CENTER, EX_W_HAT, STRESS_BAR, EXDISP(:)%W0, EXSTRESS, & 
					   (/INT(MAXGRID(1)+1), INT(MAXGRID(2)+1)/))

	!----- COMPUTE PUFEM APPROXIMATE SOLUTION -----
	CALL APPROXSOL(APDISP, APMOMENT, XCORDS, YCORDS, COEFF_APDISP, NDX)

	!----- COMPUTE APPROXIMATE NONDIMENSIONAL NUMERICAL RESULT -----
	CALL APNONDIMRESULT(AP_W_BAR_CENTER, AP_W_HAT, APDISP(:)%W0, (/INT(MAXGRID(1)+1), INT(MAXGRID(2)+1)/))
	!----- ESTIMATE RELATIVE MAXIMUM NORM ERROR -----
	
	DO I=1, NGRID
		IF (DABS(EXDISP(I)%W0) .LE. 10000.0D0*EPS) THEN
			ERROR_DISP(I)%W0 = DABS(APDISP(I)%W0 - EXDISP(I)%W0)
		ELSE
			ERROR_DISP(I)%W0 = DABS((APDISP(I)%W0 - EXDISP(I)%W0)/EXDISP(I)%W0)
		ENDIF
		IF (DABS(EXDISP(I)%PIX) .LE. 10000.0D0*EPS) THEN
			ERROR_DISP(I)%PIX = DABS(APDISP(I)%PIX - EXDISP(I)%PIX)
		ELSE
			ERROR_DISP(I)%PIX = DABS((APDISP(I)%PIX - EXDISP(I)%PIX)/EXDISP(I)%PIX)
		ENDIF
		IF (DABS(EXDISP(I)%PIY) .LE. 10000.0D0*EPS) THEN
			ERROR_DISP(I)%PIY = DABS(APDISP(I)%PIY - EXDISP(I)%PIY)
		ELSE
			ERROR_DISP(I)%PIY = DABS((APDISP(I)%PIY - EXDISP(I)%PIY)/EXDISP(I)%PIY)
		ENDIF
		
		IF (DABS(EXMOMENT(I)%MXX) .LE. 10000.0D0*EPS) THEN
			ERROR_MOMENT(I)%MXX = DABS(APMOMENT(I)%MXX - EXMOMENT(I)%MXX)
		ELSE
			ERROR_MOMENT(I)%MXX = DABS((APMOMENT(I)%MXX - EXMOMENT(I)%MXX) / EXMOMENT(I)%MXX)
		ENDIF
		IF (DABS(EXMOMENT(I)%MYY) .LE. 10000.0D0*EPS) THEN
			ERROR_MOMENT(I)%MYY = DABS(APMOMENT(I)%MYY - EXMOMENT(I)%MYY)
		ELSE
			ERROR_MOMENT(I)%MYY = DABS((APMOMENT(I)%MYY - EXMOMENT(I)%MYY) / EXMOMENT(I)%MYY)
		ENDIF
		IF (DABS(EXMOMENT(I)%MXY) .LE. 10000.0D0*EPS) THEN
			ERROR_MOMENT(I)%MXY = DABS(APMOMENT(I)%MXY - EXMOMENT(I)%MXY)
		ELSE
			ERROR_MOMENT(I)%MXY = DABS((APMOMENT(I)%MXY - EXMOMENT(I)%MXY) / EXMOMENT(I)%MXY)
		ENDIF
	ENDDO
	
	!----- INDICE WHICH INDICATE MAXIMUM NORM ERROR AT EACH ERROR
	INDICE = (/ MAXLOC(ERROR_DISP(:)%W0), MAXLOC(ERROR_DISP(:)%PIX), MAXLOC(ERROR_DISP(:)%PIY), &
			    MAXLOC(ERROR_MOMENT(:)%MXX), MAXLOC(ERROR_MOMENT(:)%MYY), MAXLOC(ERROR_MOMENT(:)%MXY) /)
	
	PRINT*, "RELATIVE MAXIMUM ERROR FOR W0 : "
	PRINT*, ERROR_DISP(INDICE(1))%W0
	PRINT*, ""
	PRINT*, "RELATIVE MAXIMUM ERROR FOR PI_X : "
	PRINT*, ERROR_DISP(INDICE(2))%PIX
	PRINT*, ""
	PRINT*, "RELATIVE MAXIMUM ERROR FOR PI_Y : "
	PRINT*, ERROR_DISP(INDICE(3))%PIY
	PRINT*, ""
	PRINT*, "NONDIMENSIONAL TRANSVERSE DEFLECTION : "
	PRINT*, ""
	PRINT*, "EXACT W BAR AT CENTER POINT"
	PRINT*, EX_W_BAR_CENTER
	PRINT*, "NUMERICAL W BAR AT CENTER POINT"
	PRINT*, AP_W_BAR_CENTER
	PRINT*, ""
	PRINT*, "RELATIVE ERROR FOR NONDIMENSIONAL NUMERICAL RESULT : "
	PRINT*, ""
	PRINT*, "W BAR AT CENTER POINT"
	PRINT*, DABS((EX_W_BAR_CENTER - AP_W_BAR_CENTER) / EX_W_BAR_CENTER)
	PRINT*, "MAX. W HAT"
	PRINT*, DABS((EX_W_HAT - AP_W_HAT) / EX_W_HAT)
	PRINT*, ""
	PRINT*, "RELATIVE MAX. ERROR FOR MOMENTS : "
	PRINT*, ""
	PRINT*, "BENDING MOMENT MXX : "
	PRINT*, ERROR_MOMENT(INDICE(4))%MXX
	PRINT*, ""
	PRINT*, "BENDING MOMENT MYY : "
	PRINT*, ERROR_MOMENT(INDICE(5))%MYY
	PRINT*, ""
	PRINT*, "BENDING MOMENT MXY : "
	PRINT*, ERROR_MOMENT(INDICE(6))%MXY
	PRINT*, ""
	
	OPEN(1, FILE='exact_w0.dat')
	OPEN(2, FILE='exact_pix.dat')
	OPEN(3, FILE='exact_piy.dat')
	
	OPEN(4, FILE='exact_Mxx.dat')
	OPEN(5, FILE='exact_Myy.dat')
	OPEN(6, FILE='exact_Mxy.dat')
	
	OPEN(7, FILE='approx_w0.dat')
	OPEN(8, FILE='approx_pix.dat')
	OPEN(9, FILE='approx_piy.dat')
	
	OPEN(10, FILE='approx_Mxx.dat')
	OPEN(11, FILE='approx_Myy.dat')
	OPEN(12, FILE='approx_Mxy.dat')
	
	OPEN(13, FILE='error_w0.dat')
	OPEN(14, FILE='error_pix.dat')
	OPEN(15, FILE='error_piy.dat')
	
	OPEN(16, FILE='error_Mxx.dat')
	OPEN(17, FILE='error_Myy.dat')
	OPEN(18, FILE='error_Mxy.dat')
	
	OPEN(19, FILE='exact_sxx.dat')
	OPEN(20, FILE='exact_syy.dat')
	OPEN(21, FILE='exact_sxy.dat')
	OPEN(22, FILE='exact_sxz.dat')
	OPEN(23, FILE='exact_syz.dat')
	
	II=1;
	DO I=1, MAXGRID(1)+1
		DO J=1, MAXGRID(2)+1
			WRITE(1,*) XCORDS(I), YCORDS(J), EXDISP(II)%W0
			WRITE(2,*) XCORDS(I), YCORDS(J), EXDISP(II)%PIX
			WRITE(3,*) XCORDS(I), YCORDS(J), EXDISP(II)%PIY
			
			WRITE(4,*) XCORDS(I), YCORDS(J), EXMOMENT(II)%MXX
			WRITE(5,*) XCORDS(I), YCORDS(J), EXMOMENT(II)%MYY
			WRITE(6,*) XCORDS(I), YCORDS(J), EXMOMENT(II)%MXY
			
			WRITE(7,*) XCORDS(I), YCORDS(J), APDISP(II)%W0
			WRITE(8,*) XCORDS(I), YCORDS(J), APDISP(II)%PIX
			WRITE(9,*) XCORDS(I), YCORDS(J), APDISP(II)%PIY
			
			WRITE(10,*) XCORDS(I), YCORDS(J), APMOMENT(II)%MXX
			WRITE(11,*) XCORDS(I), YCORDS(J), APMOMENT(II)%MYY
			WRITE(12,*) XCORDS(I), YCORDS(J), APMOMENT(II)%MXY
			
			WRITE(13,*) XCORDS(I), YCORDS(J), ERROR_DISP(II)%W0
			WRITE(14,*) XCORDS(I), YCORDS(J), ERROR_DISP(II)%PIX
			WRITE(15,*) XCORDS(I), YCORDS(J), ERROR_DISP(II)%PIY
			
			WRITE(16,*) XCORDS(I), YCORDS(J), ERROR_MOMENT(II)%MXX
			WRITE(17,*) XCORDS(I), YCORDS(J), ERROR_MOMENT(II)%MYY
			WRITE(18,*) XCORDS(I), YCORDS(J), ERROR_MOMENT(II)%MXY
			
			WRITE(19,*) XCORDS(I), YCORDS(J), EXSTRESS(II)%SXX
			WRITE(20,*) XCORDS(I), YCORDS(J), EXSTRESS(II)%SYY
			WRITE(21,*) XCORDS(I), YCORDS(J), EXSTRESS(II)%SXY
			WRITE(22,*) XCORDS(I), YCORDS(J), EXSTRESS(II)%SXZ
			WRITE(23,*) XCORDS(I), YCORDS(J), EXSTRESS(II)%SYZ
			II=II+1
		ENDDO
		WRITE(1,*) ""
		WRITE(2,*) ""
		WRITE(3,*) ""
		WRITE(4,*) ""
		WRITE(5,*) ""
		WRITE(6,*) ""
		WRITE(7,*) ""
		WRITE(8,*) ""
		WRITE(9,*) ""
		WRITE(10,*) ""
		WRITE(11,*) ""
		WRITE(12,*) ""
		WRITE(13,*) ""
		WRITE(14,*) ""
		WRITE(15,*) ""
		WRITE(16,*) ""
		WRITE(17,*) ""
		WRITE(18,*) ""
		WRITE(19,*) ""
		WRITE(20,*) ""
		WRITE(21,*) ""
		WRITE(22,*) ""
		WRITE(23,*) ""
	ENDDO
	
	CLOSE(1)
	CLOSE(2)
	CLOSE(3)
	CLOSE(4)
	CLOSE(5)
	CLOSE(6)
	CLOSE(7)
	CLOSE(8)
	CLOSE(9)
	CLOSE(10)
	CLOSE(11)
	CLOSE(12)
	CLOSE(13)
	CLOSE(14)
	CLOSE(15)
	CLOSE(16)
	CLOSE(17)
	CLOSE(18)
	CLOSE(19)
	CLOSE(20)
	CLOSE(21)
	CLOSE(22)
	CLOSE(23)
	
	OPEN(30, FILE='nondim_result.dat')
	WRITE(30,*) "W_BAR AT CENTER POINT"
	WRITE(30,*) EX_W_BAR_CENTER
	WRITE(30,*) ""
	WRITE(30,*) "MAXIMUM NONDIMENSIONAL DEFLECTION EX_W_HAT"
	WRITE(30,*) EX_W_HAT
	WRITE(30,*) ""
	WRITE(30,*) "STRESSES OF SIMPLY SUPPORTED SQUARE PLATE"
	WRITE(30,*) "SIGMA_XX : ", STRESS_BAR%SXX
	WRITE(30,*) "SIGMA_YY : ", STRESS_BAR%SYY
	WRITE(30,*) "SIGMA_XY : ", STRESS_BAR%SXY
	WRITE(30,*) "SIGMA_XZ : ", STRESS_BAR%SXZ
	WRITE(30,*) "SIGMA_YZ : ", STRESS_BAR%SYZ
	WRITE(30,*) ""
	WRITE(30,*) "-----RELATIVE MAX. ERROR FOR NONDIMENSIONAL NUMERICAL RESULT-----"
	WRITE(30,*) "W BAR AT CENTER POINT"
	WRITE(30,*) DABS((EX_W_BAR_CENTER - AP_W_BAR_CENTER) / EX_W_BAR_CENTER)
	WRITE(30,*) "MAX. W HAT"
	WRITE(30,*) DABS((EX_W_HAT - AP_W_HAT) / EX_W_HAT)
	CLOSE(30)
	
	OPEN(300, FILE='error.dat')
	WRITE(300,*) "RELATIVE MAXIMUM ERROR FOR W0 : "
	WRITE(300,*) ERROR_DISP(INDICE(1))%W0
	WRITE(300,*) ""
	WRITE(300,*) "RELATIVE MAXIMUM ERROR FOR PI_X : "
	WRITE(300,*) ERROR_DISP(INDICE(2))%PIX
	WRITE(300,*) ""
	WRITE(300,*) "RELATIVE MAXIMUM ERROR FOR PI_Y : "
	WRITE(300,*) ERROR_DISP(INDICE(3))%PIY
	CLOSE(300)
	
	DEALLOCATE(XCORDS, YCORDS, EXDISP, EXMOMENT, APDISP, ERROR_DISP, EXSTRESS, APMOMENT)

END SUBROUTINE MAXNORM

END MODULE ERRORESTIMATE

