! FILE WRITTEN BY HYUNJU KIM
!
! DATE : FRI 9 2009

MODULE ASSEMBLE

    USE NEWTYPE
    USE GLBVAR
    USE GSQUAD
    USE PACKAGE
    USE LOADFUNCTION
    USE INTEGRATION

    IMPLICIT NONE
		
CONTAINS

! LET'S ASSEMBLE THE STIFFNESS MATRIX USING THE MODULE INTEGRATION

SUBROUTINE STIF(K)

	TYPE(SUBMAT), INTENT(OUT) :: K
    TYPE(INT2D) :: SF_INDX_I, SF_INDX_J
    INTEGER :: I, II, J, JJ, KK(6), NDX(3,DOF)

!	SPLIT INTEGRAL SUB-PATCHES
    TYPE(INTPATCH) :: INTPATCHGROUP(NUMPATCHES,NUMPATCHES,NUMINTSUBPATCH)
	INTEGER :: NINTPATCHGROUP(NUMPATCHES,NUMPATCHES)

!	GAUSS POINTS
    REAL*8 :: X(NGAUSSPT), W(NGAUSSPT), TMP1
    
	200 FORMAT(2000(F30.16, 1X))

     PRINT *,
     PRINT *, 'ASSEMBLE THE STIFFNESS MATRIX'

!-------- EVALUATE THE GAUSS POINTS AND WEIGHTS IN REFERENCE LINE [-1, 1]----------
    CALL GAULEG(-1.0D0,1.0D0,X,W,NGAUSSPT)

!---------CONSTRUCT THE TABLE WHICH IS CONSIST OF INTERSECTION SUBCUBOIDS FOR
!            EACH PATCHES
    CALL INTDOMAINTABLE(INTPATCHGROUP, NINTPATCHGROUP)
    OPEN(1, FILE='intpatchgroup.dat')
    DO I=1,NUMPATCHES
    		DO J=1, NUMPATCHES
		    WRITE(1,*) (INTPATCHGROUP(I, J, JJ), JJ=1,NUMINTSUBPATCH)
		ENDDO
	ENDDO
	CLOSE(1)

!---------CONSTRUCT THE INDEX TABLE WHICH HAS PATCH INFORMATION(i.e PU INFORMATION)
!            AND INTERPOLATION DEGREE FOR EACH STIFFNESS ELEMENTS
    CALL STIFINDEX(NDX)
	
    !---------------INITIALIZE--------------
    KK(:) = 0
   	K%R11(:) = 0; K%R22(:) = 0; K%R33(:) = 0
   	K%C11(:) = 0; K%C22(:) = 0; K%C33(:) = 0
   	K%K11(:) = 0.0D0; K%K22(:) = 0.0D0; K%K33(:) = 0.0D0

   	K%R12(:) = 0; K%R13(:) = 0; K%R23(:) = 0
   	K%C12(:) = 0; K%C13(:) = 0; K%C23(:) = 0
   	K%K12(:) = 0.0D0; K%K13(:) = 0.0D0; K%K23(:) = 0.0D0

!!!!!!!!! SUB MATRIX [K11], [K22], [K33] !!!!!!!!!!
    DO I = 1, DOF
        SF_INDX_I = INT2D(NDX(2,I), NDX(3,I))
		DO J = 1, DOF
			SF_INDX_J = INT2D(NDX(2,J), NDX(3,J))
			IF (J.GE.I) THEN
			!---------------SUB MATRIX [K11]-------------------
				TMP1 = INTEGRATION_K(BGMESH(NDX(1,I)), BGMESH(NDX(1,J)), SF_INDX_I, SF_INDX_J, &
					   INTPATCHGROUP(NDX(1,I),NDX(1,J),:), NINTPATCHGROUP(NDX(1,I),NDX(1,J)), IORDER, X, W, NGAUSSPT, 11)
				IF (DABS(TMP1) .GT. EPS) THEN
				    KK(1) = KK(1) + 1
				    K%R11(KK(1)) = I; K%C11(KK(1)) = J; K%K11(KK(1)) = TMP1
				ENDIF
			!---------------SUB MATRIX [K22]-------------------
				TMP1 = INTEGRATION_K(BGMESH(NDX(1,I)), BGMESH(NDX(1,J)), SF_INDX_I, SF_INDX_J, &
					   INTPATCHGROUP(NDX(1,I),NDX(1,J),:), NINTPATCHGROUP(NDX(1,I),NDX(1,J)), IORDER, X, W, NGAUSSPT, 22)
				IF (DABS(TMP1) .GT. EPS) THEN
				    KK(2) = KK(2) + 1
				    K%R22(KK(2)) = I; K%C22(KK(2)) = J; K%K22(KK(2)) = TMP1
				ENDIF
			!---------------SUB MATRIX [K33]-------------------
				TMP1 = INTEGRATION_K(BGMESH(NDX(1,I)), BGMESH(NDX(1,J)), SF_INDX_I, SF_INDX_J, &
					   INTPATCHGROUP(NDX(1,I),NDX(1,J),:), NINTPATCHGROUP(NDX(1,I),NDX(1,J)), IORDER, X, W, NGAUSSPT, 33)
				IF (DABS(TMP1) .GT. EPS) THEN
				    KK(3) = KK(3) + 1
				    K%R33(KK(3)) = I; K%C33(KK(3)) = J; K%K33(KK(3)) = TMP1
				ENDIF
			ENDIF
			!---------------SUB MATRIX [K12]-------------------
				TMP1 = INTEGRATION_K(BGMESH(NDX(1,I)), BGMESH(NDX(1,J)), SF_INDX_I, SF_INDX_J, &
					   INTPATCHGROUP(NDX(1,I),NDX(1,J),:), NINTPATCHGROUP(NDX(1,I),NDX(1,J)), IORDER, X, W, NGAUSSPT, 12)
		    IF (DABS(TMP1) .GT. EPS) THEN
		        KK(4) = KK(4) + 1
		        K%R12(KK(4)) = I; K%C12(KK(4)) = J; K%K12(KK(4)) = TMP1
		    ENDIF
			!---------------SUB MATRIX [K13]-------------------
				TMP1 = INTEGRATION_K(BGMESH(NDX(1,I)), BGMESH(NDX(1,J)), SF_INDX_I, SF_INDX_J, &
					   INTPATCHGROUP(NDX(1,I),NDX(1,J),:), NINTPATCHGROUP(NDX(1,I),NDX(1,J)), IORDER, X, W, NGAUSSPT, 13)
		    IF (DABS(TMP1) .GT. EPS) THEN
		        KK(5) = KK(5) + 1
		        K%R13(KK(5)) = I; K%C13(KK(5)) = J; K%K13(KK(5)) = TMP1
		    ENDIF
			!---------------SUB MATRIX [K23]-------------------
				TMP1 = INTEGRATION_K(BGMESH(NDX(1,I)), BGMESH(NDX(1,J)), SF_INDX_I, SF_INDX_J, &
					   INTPATCHGROUP(NDX(1,I),NDX(1,J),:), NINTPATCHGROUP(NDX(1,I),NDX(1,J)), IORDER, X, W, NGAUSSPT, 23)
		    IF (DABS(TMP1) .GT. EPS) THEN
		        KK(6) = KK(6) + 1
		        K%R23(KK(6)) = I; K%C23(KK(6)) = J; K%K23(KK(6)) = TMP1
		    ENDIF
		ENDDO
    ENDDO
	
	K%NZ(:) = KK(:)
	
END SUBROUTINE STIF

SUBROUTINE LOADVEC(F)

    REAL*8, INTENT(OUT) :: F(INT(3*DOF))
    TYPE(INTPATCH) :: INTPATCHGROUP(NUMPATCHES,NUMPATCHES,NUMINTSUBPATCH)
    TYPE(INT2D) :: SF_INDX_I
    INTEGER :: I, NINTPATCHGROUP(NUMPATCHES,NUMPATCHES), NDX(3,DOF)
    REAL*8 :: X(NGAUSSPT), W(NGAUSSPT)

     PRINT *,
     PRINT *, 'ASSEMBLE THE LOAD VECTOR'

!-------- EVALUATE THE GAUSS POINTS AND WEIGHTS IN REFERENCE LINE [-1, 1]----------
    CALL GAULEG(-1.0D0,1.0D0,X,W,NGAUSSPT)
!---------CONSTRUCT THE TABLE WHICH IS CONSIST OF INTERSECTION SUBCUBOIDS FOR
!            EACH PATCHES
    CALL INTDOMAINTABLE(INTPATCHGROUP, NINTPATCHGROUP)
!---------CONSTRUCT THE INDEX TABLE WHICH HAS PATCH INFORMATION(i.e PU INFORMATION)
!            AND INTERPOLATION DEGREE FOR EACH STIFFNESS ELEMENTS
    CALL STIFINDEX(NDX)

    DO I=1, DOF
        SF_INDX_I = INT2D(NDX(2,I), NDX(3,I))
    !---------------SUB LOAD VECTOR [F1]-------------------
        F(I) = INTEGRATION_F(BGMESH(NDX(1,I)), SF_INDX_I, INTPATCHGROUP(NDX(1,I),NDX(1,I),:), &
					         NINTPATCHGROUP(NDX(1,I),NDX(1,I)), IORDER, X, W, NGAUSSPT, 1)
    !---------------SUB LOAD VECTOR [F2]-------------------
    	F(DOF+I) = 0.0D0
!        F(I) = INTEGRATION_F(BGMESH(NDX(1,I)), SF_INDX_I, INTPATCHGROUP(NDX(1,I),NDX(1,I),:), &
!					         NINTPATCHGROUP(NDX(1,I),NDX(1,I)), IORDER, X, W, NGAUSSPT, 1)

    !---------------SUB LOAD VECTOR [F3]-------------------
		F(2*DOF+I) = 0.0D0    
!        F(I) = INTEGRATION_F(BGMESH(NDX(1,I)), SF_INDX_I, INTPATCHGROUP(NDX(1,I),NDX(1,I),:), &
!					         NINTPATCHGROUP(NDX(1,I),NDX(1,I)), IORDER, X, W, NGAUSSPT, 1)
    ENDDO

END SUBROUTINE LOADVEC

END MODULE ASSEMBLE
