MODULE EXACTSOL

	USE NEWTYPE
	USE GLBVAR
	USE LOADFUNCTION
	
	IMPLICIT NONE
	
CONTAINS

! SOLUTION OF THE REISSNER-MINDLIN MODEL OF THE SEIM-INFINITE PLATE PROBLEM
! (FROM REF. "EDGE EFFECTS IN THE REISSNER-MINDLIN PLATE THEORY")

SUBROUTINE ANALYTICSOL(SOL, XCORDS, YCORDS)
	REAL*8, INTENT(IN) :: XCORDS(:), YCORDS(:)
	TYPE(DISPLACEMENT), INTENT(OUT) :: SOL(:)
!	TYPE(MOMENT), INTENT(OUT) :: MOMENTS(:)
	INTEGER :: NUM_XCORDS, NUM_YCORDS, VEC_N, I, J, II, JJ, KK
	REAL*8 :: Q, D, C(4), VAR(4)

	D = STRESS_D(1,1) ! PLATE CONSTANT
	Q = LOAD_Q

	!---- DEFINE THE COEFFICIENTS C1 ~ C4 -----
	CALL GET_COEFFOFEXACTSOL(C)

	NUM_XCORDS = UBOUND(XCORDS,1)
	NUM_YCORDS = UBOUND(YCORDS,1)
	VEC_N = NUM_XCORDS*NUM_YCORDS
	
	DO I=1, VEC_N
		SOL(I) = DISPLACEMENT(0.0D0, 0.0D0, 0.0D0)
!		MOMENTS(I) = MOMENT(0.0D0, 0.0D0, 0.0D0)
	ENDDO
	
	PRINT*, ""
	PRINT*, "COEFFICIENTS OF TRUE SOLUTION"
	PRINT*, "C(1) = ", C(1)
	PRINT*, "C(2) = ", C(2)
	PRINT*, "C(3) = ", C(3)
	PRINT*, "C(4) = ", C(4)
	PRINT*, ""
	
	KK = 1
	DO II=1, NUM_XCORDS
		VAR(1) = DSIN(XCORDS(II) / L)
		VAR(2) = DCOS(XCORDS(II) / L)
		DO JJ=1, NUM_YCORDS
			VAR(3) = DEXP(YCORDS(JJ) / L)
			VAR(4) = DEXP(GAMMA*YCORDS(JJ) / h)
			SOL(KK)%PIX = (Q*L**5 / h**3)*(-(h**3 / (D*L**2)) - C(1)*VAR(3) - C(2)*(-YCORDS(JJ) / L)*VAR(3) + &
						  C(3)*(h**2*VAR(3) / (KS*G(1)*L**4)) - C(4)*(GAMMA*h*VAR(4) / (KS*G(1)*L**3)))*VAR(1)
			
			SOL(KK)%PIY = (Q*L**5 / h**3)*(-C(1)*VAR(3) + C(2)*(1.0D0 - (-YCORDS(JJ) / L))*VAR(3) + C(3)*(h**2* &
						  VAR(3) / (KS*G(1)*L**4)) - C(4)*(h**2*VAR(4) / (KS*G(1)*L**4)))*VAR(2)
	
			SOL(KK)%W0 = L*((Q*L**5)/h**3)*((h**3/(D*L**2)) + (h**2/(KS*G(1)*L**4)) + C(1)*VAR(3) + &
						 C(2)*((2.0D0*D/ (KS*G(1)*L**2*h)) + (-YCORDS(JJ) / L))*VAR(3) - C(3)* &
						 (h**2*VAR(3) / (KS*G(1)*L**4)))*VAR(2)
			KK = KK + 1
		ENDDO
	ENDDO

END SUBROUTINE ANALYTICSOL

END MODULE EXACTSOL

