	MODULE INTEGRATION

    USE NEWTYPE
    USE GLBVAR
    USE PU
    USE INTERPOLATION
    USE GSQUAD
    USE PACKAGE

    IMPLICIT NONE

CONTAINS

!------------------INTEGRAL CODE FOR THE STIFFNESS MATRIX ELEMENT--------------
REAL*8 FUNCTION INTEGRATION_K(BGMESH_I, BGMESH_J, SF_INDX_I, SF_INDX_J, INTPATCHES, &
							  NINTPATCHES, INTERORDER, X, W, N, SUB_MATRIX_INDX)

    TYPE(INTPATCH), INTENT(IN) :: INTPATCHES(NUMINTSUBPATCH)
    TYPE(RECPATCH), INTENT(IN) :: BGMESH_I, BGMESH_J
    TYPE(INT2D), INTENT(IN) :: SF_INDX_I, SF_INDX_J
    INTEGER, INTENT(IN) :: NINTPATCHES, INTERORDER, SUB_MATRIX_INDX, N
    REAL*8, INTENT(IN) :: X(N), W(N)
    TYPE(FVALUE), ALLOCATABLE :: SF_I(:), SF_J(:), PU_I(:), PU_J(:)
    TYPE(TRANSFORM2D), ALLOCATABLE :: GSPT(:)
    REAL*8, ALLOCATABLE :: WEIGHT(:)
    REAL*8 :: DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, DIFF_XN, DIFF_YN, DIFF_NX, DIFF_NY, DIFF_NN
    INTEGER :: I,J, II, JJ, KK

	INTEGRATION_K=0.0D0
	ALLOCATE(PU_I(N**2), PU_J(N**2), SF_I(N**2), SF_J(N**2), GSPT(N**2), WEIGHT(N**2))
	
	!!!!!!!!!!!!!!!!!!!!!!!!!!! SUB MATRIX [K11] OR [K22] OR [K33] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	IF (SUB_MATRIX_INDX.EQ.11 .OR. SUB_MATRIX_INDX.EQ.22 .OR. SUB_MATRIX_INDX.EQ.33) THEN
		DO II=1, NINTPATCHES
		    KK=0
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
		    DO I=1,N
		        DO J=1,N
		            KK=KK+1
		            GSPT(KK)=REF2PHY(POINT2D(X(I),X(J)), INTPATCHES(II)%SUBPATCH)
		            WEIGHT(KK)=W(I)*W(J)
		    	ENDDO
		    ENDDO
	!--------------------EVALUATE PU AND SF AT EACH GAUSS POINT----------------
		    CALL PHYSF(SF_I, GSPT(:)%PT, N**2, SF_INDX_I, INTERORDER, OMEGA.AND.(BGMESH_I+DELTA))
		    CALL PHYSF(SF_J, GSPT(:)%PT, N**2, SF_INDX_J, INTERORDER, OMEGA.AND.(BGMESH_J+DELTA))

			CALL PHYPU(PU_I, GSPT(:)%PT, N**2, BGMESH_I+DELTA)
			CALL PHYPU(PU_J, GSPT(:)%PT, N**2, BGMESH_J+DELTA)
	
	!--------------------EVALUATE WEIGHT AT EACH GAUSS POINT----------------
			PU_I(:)%D00 = PRODUCT(RESHAPE((/PU_I(:)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D10 = PRODUCT(RESHAPE((/PU_I(:)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D01 = PRODUCT(RESHAPE((/PU_I(:)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			
	!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
			DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D10, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D10, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))
					  			  
			DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D01, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D01, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2))
			
			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2), &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2))
			
			IF (SUB_MATRIX_INDX.EQ.11) THEN
				INTEGRATION_K = INTEGRATION_K + GSPT(1)%JACOBIAN*(KS*SHEAR_A(2,2)*DIFF_XX + KS*SHEAR_A(1,1)*DIFF_YY &
								+ HOOKS_K*DIFF_NN)
			ELSEIF (SUB_MATRIX_INDX.EQ.22) THEN
				INTEGRATION_K = INTEGRATION_K + GSPT(1)%JACOBIAN*(STRESS_D(1,1)*DIFF_XX + STRESS_D(3,3)*DIFF_YY & 
								+ KS*SHEAR_A(2,2)*DIFF_NN)
			ELSEIF (SUB_MATRIX_INDX.EQ.33) THEN
				INTEGRATION_K = INTEGRATION_K + GSPT(1)%JACOBIAN*(STRESS_D(3,3)*DIFF_XX + STRESS_D(2,2)*DIFF_YY & 
								+ KS*SHEAR_A(1,1)*DIFF_NN)
			ENDIF
		ENDDO
		
	!!!!!!!!!!!!!!!!!!!!!!!!!!! SUB MATRIX [K12]=[K21]^T !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	ELSEIF (SUB_MATRIX_INDX.EQ.12) THEN
		DO II=1, NINTPATCHES
		    KK=0
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
		    DO I=1,N
		        DO J=1,N
		            KK=KK+1
		            GSPT(KK)=REF2PHY(POINT2D(X(I),X(J)), INTPATCHES(II)%SUBPATCH)
		            WEIGHT(KK)=W(I)*W(J)
		    	ENDDO
		    ENDDO
	!--------------------EVALUATE PU AND SF AT EACH GAUSS POINT----------------
		    CALL PHYSF(SF_I, GSPT(:)%PT, N**2, SF_INDX_I, INTERORDER, OMEGA.AND.(BGMESH_I+DELTA))
		    CALL PHYSF(SF_J, GSPT(:)%PT, N**2, SF_INDX_J, INTERORDER, OMEGA.AND.(BGMESH_J+DELTA))

			CALL PHYPU(PU_I, GSPT(:)%PT, N**2, BGMESH_I+DELTA)
			CALL PHYPU(PU_J, GSPT(:)%PT, N**2, BGMESH_J+DELTA)
	
	!--------------------EVALUATE WEIGHT AT EACH GAUSS POINT----------------
			PU_I(:)%D00 = PRODUCT(RESHAPE((/PU_I(:)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D10 = PRODUCT(RESHAPE((/PU_I(:)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D01 = PRODUCT(RESHAPE((/PU_I(:)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			
	!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
			DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2), &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D10, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))

			INTEGRATION_K = INTEGRATION_K + GSPT(1)%JACOBIAN*(KS*SHEAR_A(2,2)*DIFF_NX)
		ENDDO
			
	!!!!!!!!!!!!!!!!!!!!!!!!!!! SUB MATRIX [K13]=[K31]^T !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	ELSEIF (SUB_MATRIX_INDX.EQ.13) THEN
		DO II=1, NINTPATCHES
		    KK=0
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
		    DO I=1,N
		        DO J=1,N
		            KK=KK+1
		            GSPT(KK)=REF2PHY(POINT2D(X(I),X(J)), INTPATCHES(II)%SUBPATCH)
		            WEIGHT(KK)=W(I)*W(J)
		    	ENDDO
		    ENDDO
	!--------------------EVALUATE PU AND SF AT EACH GAUSS POINT----------------
		    CALL PHYSF(SF_I, GSPT(:)%PT, N**2, SF_INDX_I, INTERORDER, OMEGA.AND.(BGMESH_I+DELTA))
		    CALL PHYSF(SF_J, GSPT(:)%PT, N**2, SF_INDX_J, INTERORDER, OMEGA.AND.(BGMESH_J+DELTA))

			CALL PHYPU(PU_I, GSPT(:)%PT, N**2, BGMESH_I+DELTA)
			CALL PHYPU(PU_J, GSPT(:)%PT, N**2, BGMESH_J+DELTA)
	
	!--------------------EVALUATE WEIGHT AT EACH GAUSS POINT----------------
			PU_I(:)%D00 = PRODUCT(RESHAPE((/PU_I(:)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D10 = PRODUCT(RESHAPE((/PU_I(:)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D01 = PRODUCT(RESHAPE((/PU_I(:)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			
	!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
			DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2), &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D01, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2))

			INTEGRATION_K = INTEGRATION_K + GSPT(1)%JACOBIAN*(KS*SHEAR_A(1,1)*DIFF_NY)
		ENDDO

	!!!!!!!!!!!!!!!!!!!!!!!!!!! SUB MATRIX [K23]=[K32]^T !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	ELSEIF (SUB_MATRIX_INDX.EQ.23) THEN
		DO II=1, NINTPATCHES
		    KK=0
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
		    DO I=1,N
		        DO J=1,N
		            KK=KK+1
		            GSPT(KK)=REF2PHY(POINT2D(X(I),X(J)), INTPATCHES(II)%SUBPATCH)
		            WEIGHT(KK)=W(I)*W(J)
		    	ENDDO
		    ENDDO
	!--------------------EVALUATE PU AND SF AT EACH GAUSS POINT----------------
		    CALL PHYSF(SF_I, GSPT(:)%PT, N**2, SF_INDX_I, INTERORDER, OMEGA.AND.(BGMESH_I+DELTA))
		    CALL PHYSF(SF_J, GSPT(:)%PT, N**2, SF_INDX_J, INTERORDER, OMEGA.AND.(BGMESH_J+DELTA))

			CALL PHYPU(PU_I, GSPT(:)%PT, N**2, BGMESH_I+DELTA)
			CALL PHYPU(PU_J, GSPT(:)%PT, N**2, BGMESH_J+DELTA)
	
	!--------------------EVALUATE WEIGHT AT EACH GAUSS POINT----------------
			PU_I(:)%D00 = PRODUCT(RESHAPE((/PU_I(:)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D10 = PRODUCT(RESHAPE((/PU_I(:)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D01 = PRODUCT(RESHAPE((/PU_I(:)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			
	!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
			DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D01, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
								  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D10, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))

			DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D10, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
								  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D01, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2))
					  			  
			INTEGRATION_K = INTEGRATION_K + GSPT(1)%JACOBIAN*(STRESS_D(1,2)*DIFF_YX + STRESS_D(3,3)*DIFF_XY)
		ENDDO
	ENDIF
	
	DEALLOCATE(PU_I, PU_J, SF_I, SF_J, GSPT, WEIGHT)
	
END FUNCTION INTEGRATION_K

!------------------INTEGRAL CODE FOR GEOMETRICAL STIFFNESS MATRIX--------------
REAL*8 FUNCTION INTEGRATION_KG(BGMESH_I, BGMESH_J, SF_INDX_I, SF_INDX_J, INTPATCHES, &
							  NINTPATCHES, INTERORDER, X, W, N)

    TYPE(INTPATCH), INTENT(IN) :: INTPATCHES(NUMINTSUBPATCH)
    TYPE(RECPATCH), INTENT(IN) :: BGMESH_I, BGMESH_J
    TYPE(INT2D), INTENT(IN) :: SF_INDX_I, SF_INDX_J
    INTEGER, INTENT(IN) :: NINTPATCHES, INTERORDER, N
    REAL*8, INTENT(IN) :: X(N), W(N)
    TYPE(FVALUE), ALLOCATABLE :: SF_I(:), SF_J(:), PU_I(:), PU_J(:)
    TYPE(TRANSFORM2D), ALLOCATABLE :: GSPT(:)
    REAL*8, ALLOCATABLE :: WEIGHT(:)
    REAL*8 :: DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX
    INTEGER :: I, J, II, JJ, KK
    
    INTEGRATION_KG=0.0D0

	ALLOCATE(PU_I(N**2), SF_I(N**2), PU_J(N**2), SF_J(N**2), GSPT(N**2), WEIGHT(N**2))

	DO II=1, NINTPATCHES
	    KK=0
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
	    DO I=1,N
	        DO J=1,N
	            KK=KK+1
	            GSPT(KK)=REF2PHY(POINT2D(X(I),X(J)), INTPATCHES(II)%SUBPATCH)
	            WEIGHT(KK)=W(I)*W(J)
	        ENDDO
	    ENDDO
	!--------------------EVALUATE PU AND SF AT EACH GAUSS POINT----------------
		    CALL PHYSF(SF_I, GSPT(:)%PT, N**2, SF_INDX_I, INTERORDER, OMEGA.AND.(BGMESH_I+DELTA))
		    CALL PHYSF(SF_J, GSPT(:)%PT, N**2, SF_INDX_J, INTERORDER, OMEGA.AND.(BGMESH_J+DELTA))

			CALL PHYPU(PU_I, GSPT(:)%PT, N**2, BGMESH_I+DELTA)
			CALL PHYPU(PU_J, GSPT(:)%PT, N**2, BGMESH_J+DELTA)
	
	!--------------------EVALUATE WEIGHT AT EACH GAUSS POINT----------------
			PU_I(:)%D00 = PRODUCT(RESHAPE((/PU_I(:)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D10 = PRODUCT(RESHAPE((/PU_I(:)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			PU_I(:)%D01 = PRODUCT(RESHAPE((/PU_I(:)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			
	!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
			DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D10, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D10, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))
					  			  
			DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D01, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D01, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2))

			DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D01, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
								  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D10, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))

			DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D10, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
								  PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D10/), (/N**2, 2/), ORDER=ORDER1), 2),  &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D01, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2) + &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D01/), (/N**2, 2/), ORDER=ORDER1), 2))

		INTEGRATION_KG = INTEGRATION_KG + GSPT(1)%JACOBIAN*&
										 (STRESS_N(1)*DIFF_XX + STRESS_N(3)*DIFF_XY + STRESS_N(3)*DIFF_YX + STRESS_N(2)*DIFF_YY)
	ENDDO
		
	DEALLOCATE(PU_I, SF_I, PU_J, SF_J, GSPT, WEIGHT)
		
END FUNCTION INTEGRATION_KG

!------------------INTEGRAL CODE FOR MASS MATRIX--------------
REAL*8 FUNCTION INTEGRATION_M(BGMESH_I, BGMESH_J, SF_INDX_I, SF_INDX_J, INTPATCHES, &
							  NINTPATCHES, INTERORDER, X, W, N)

    TYPE(INTPATCH), INTENT(IN) :: INTPATCHES(NUMINTSUBPATCH)
    TYPE(RECPATCH), INTENT(IN) :: BGMESH_I, BGMESH_J
    TYPE(INT2D), INTENT(IN) :: SF_INDX_I, SF_INDX_J
    INTEGER, INTENT(IN) :: NINTPATCHES, INTERORDER, N
    REAL*8, INTENT(IN) :: X(N), W(N)
    TYPE(FVALUE), ALLOCATABLE :: SF_I(:), SF_J(:), PU_I(:), PU_J(:)
    TYPE(TRANSFORM2D), ALLOCATABLE :: GSPT(:)
    REAL*8, ALLOCATABLE :: WEIGHT(:)
    REAL*8 :: DIFF_NN
    INTEGER :: I, J, II, JJ, KK
    
    INTEGRATION_M=0.0D0

	ALLOCATE(PU_I(N**2), SF_I(N**2), PU_J(N**2), SF_J(N**2), GSPT(N**2), WEIGHT(N**2))

	DO II=1, NINTPATCHES
	    KK=0
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
	    DO I=1,N
	        DO J=1,N
	            KK=KK+1
	            GSPT(KK)=REF2PHY(POINT2D(X(I),X(J)), INTPATCHES(II)%SUBPATCH)
	            WEIGHT(KK)=W(I)*W(J)
	        ENDDO
	    ENDDO
	!--------------------EVALUATE PU AND SF AT EACH GAUSS POINT----------------
		    CALL PHYSF(SF_I, GSPT(:)%PT, N**2, SF_INDX_I, INTERORDER, OMEGA.AND.(BGMESH_I+DELTA))
		    CALL PHYSF(SF_J, GSPT(:)%PT, N**2, SF_INDX_J, INTERORDER, OMEGA.AND.(BGMESH_J+DELTA))

			CALL PHYPU(PU_I, GSPT(:)%PT, N**2, BGMESH_I+DELTA)
			CALL PHYPU(PU_J, GSPT(:)%PT, N**2, BGMESH_J+DELTA)
	
	!--------------------EVALUATE WEIGHT AT EACH GAUSS POINT----------------
			PU_I(:)%D00 = PRODUCT(RESHAPE((/PU_I(:)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1),2)
			
	!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2), &
					  			  PRODUCT(RESHAPE((/PU_J(:)%D00, SF_J(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2))

		INTEGRATION_M = INTEGRATION_M + GSPT(1)%JACOBIAN*DIFF_NN
	ENDDO
		
	DEALLOCATE(PU_I, SF_I, PU_J, SF_J, GSPT, WEIGHT)
		
END FUNCTION INTEGRATION_M

!------------------INTEGRATION ON R.H.S. WITH BOUNDARY INTEGRATION--------------
REAL*8 FUNCTION INTEGRATION_F(BGMESH_I, SF_INDX_I, INTPATCHES, NINTPATCHES, INTERORDER, & 
							  X, W, N, SUB_FORCE_VECTOR_INDX)

    USE LOADFUNCTION

    TYPE(RECPATCH), INTENT(IN) :: BGMESH_I
    TYPE(INTPATCH), INTENT(IN) :: INTPATCHES(NUMINTSUBPATCH)
    TYPE(INT2D), INTENT(IN) :: SF_INDX_I
    INTEGER, INTENT(IN) :: NINTPATCHES, INTERORDER, N, SUB_FORCE_VECTOR_INDX
    REAL*8, INTENT(IN) :: X(N), W(N)
    TYPE(FVALUE), ALLOCATABLE :: PU_I(:), SF_I(:)
    TYPE(TRANSFORM2D), ALLOCATABLE :: GSPT(:)
    REAL*8, ALLOCATABLE :: LOAD_Q_VEC(:), WEIGHT(:)
    REAL*8 :: DIFF_NN
    INTEGER :: I, J, II, JJ, KK
    
    INTEGRATION_F=0.0D0

	ALLOCATE(PU_I(N**2), SF_I(N**2), GSPT(N**2), WEIGHT(N**2), LOAD_Q_VEC(N**2))

	DO II=1, NINTPATCHES
	    KK=0
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
	    DO I=1,N
	        DO J=1,N
	            KK=KK+1
	            GSPT(KK)=REF2PHY(POINT2D(X(I),X(J)), INTPATCHES(II)%SUBPATCH)
	            WEIGHT(KK)=W(I)*W(J)
	        ENDDO
	    ENDDO
	!--------------------EVALUATE PU AND SF AT EACH GAUSS POINT----------------
	    CALL PHYPU(PU_I, GSPT(:)%PT, N**2,  BGMESH_I+DELTA)
	    CALL PHYSF(SF_I, GSPT(:)%PT, N**2, SF_INDX_I, INTERORDER, OMEGA.AND.(BGMESH_I+DELTA))
		CALL LDFT(LOAD_Q_VEC(:), GSPT(:)%PT, N**2)
	!--------------------EVALUATE PU*INTERPOLATION AT EACH GAUSS POINT----------
		DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/PU_I(:)%D00, SF_I(:)%D00/), (/N**2, 2/), ORDER=ORDER1), 2), &
				  			  PRODUCT(RESHAPE((/LOAD_Q_VEC(:), WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2))

		INTEGRATION_F = INTEGRATION_F + GSPT(1)%JACOBIAN*DIFF_NN
	ENDDO

	DEALLOCATE(PU_I, SF_I, GSPT, WEIGHT, LOAD_Q_VEC)
		
END FUNCTION INTEGRATION_F

END MODULE INTEGRATION



