MODULE PLOT
    USE NEWTYPE
    USE GLBVAR
    IMPLICIT NONE

CONTAINS

SUBROUTINE PLOTDOMAIN()
	
	OPEN(1, FILE='OMEGA')
	WRITE(1,*) OMEGA%PT1%X, OMEGA%PT1%Y
	WRITE(1,*) OMEGA%PT2%X, OMEGA%PT2%Y
	WRITE(1,*) OMEGA%PT3%X, OMEGA%PT3%Y
	WRITE(1,*) OMEGA%PT4%X, OMEGA%PT4%Y
	WRITE(1,*) OMEGA%PT1%X, OMEGA%PT1%Y
	CLOSE(1)
END SUBROUTINE PLOTDOMAIN

SUBROUTINE PLOTBGMESH()
	INTEGER :: I

	DO I=1, NUMPATCHES
		OPEN(1, FILE='bgmesh.dat')
		WRITE(1,*) BGMESH(I)%PT1%X, BGMESH(I)%PT1%Y
		WRITE(1,*) BGMESH(I)%PT2%X, BGMESH(I)%PT2%Y
		WRITE(1,*) BGMESH(I)%PT3%X, BGMESH(I)%PT3%Y
		WRITE(1,*) BGMESH(I)%PT4%X, BGMESH(I)%PT4%Y
		WRITE(1,*) BGMESH(I)%PT1%X, BGMESH(I)%PT1%Y
		WRITE(1,*) 
	ENDDO
	CLOSE(1)
END SUBROUTINE PLOTBGMESH

END MODULE PLOT
