MODULE ERRORESTIMATE

	USE EXACTSOL
	USE PACKAGE

    IMPLICIT NONE
    
CONTAINS

!----MAX. NORM ESTIMATE----
SUBROUTINE MAXNORM(COEFF_APDISP)

	REAL*8, INTENT(IN) :: COEFF_APDISP(3*DOF)
	TYPE(POINT2D) :: MESH
	INTEGER :: II, I, J, NDX(3,DOF), INDICE(6), NGRID, MAXGRID(2), MAX_INDICE(6)
	TYPE(DISPLACEMENT), ALLOCATABLE :: EXDISP(:), APDISP(:), ERROR_DISP(:)
	TYPE(MOMENT), ALLOCATABLE :: EXMOMENT(:), APMOMENT(:), ERROR_MOMENT(:)
	TYPE(STRESS), ALLOCATABLE :: EXSTRESS(:)
	REAL*8, ALLOCATABLE :: XCORDS(:), YCORDS(:)
	REAL*8 :: EXMAXWBAR, EX_W_HAT, APMAXWBAR, AP_W_HAT
	TYPE(STRESS) :: STRESS_BAR
	
	PRINT*, ""
	PRINT*, "ERROR ESTIMATES"
	PRINT*, ""
	
    CALL STIFINDEX(NDX)
    
	MAXGRID = (99,99)
	
	ALLOCATE(XCORDS(MAXGRID(1)+1), YCORDS(MAXGRID(2)+1))
	NGRID = UBOUND(XCORDS,1)*UBOUND(YCORDS,1)

	ALLOCATE(ERROR_DISP(NGRID), EXMOMENT(NGRID))
	ALLOCATE(EXDISP(NGRID), APDISP(NGRID), APMOMENT(NGRID))
	ALLOCATE(EXSTRESS(NGRID), ERROR_MOMENT(NGRID))
		
	MESH=POINT2D((OMEGA%PT2%X-OMEGA%PT1%X)/MAXGRID(1), (OMEGA%PT4%Y-OMEGA%PT1%Y)/MAXGRID(2))
	
	DO II=1, MAXGRID(1)+1
		XCORDS(II)=OMEGA%PT1%X+MESH%X*(II-1)
	ENDDO
	
	DO II=1, MAXGRID(2)+1
		YCORDS(II)=OMEGA%PT1%Y+MESH%Y*(II-1)
	ENDDO

	!----- COMPUTE FOURIER SERIES OF ANALYTIC SOLUTION -----
	CALL NAVIERSOL(EXDISP, EXMOMENT, EXSTRESS, XCORDS, YCORDS, MAXTERM, MAXTERM)

	!----- COMPUTE ANALYTIC NONDIMENSIONAL NUMERICAL RESULT -----
	CALL EXNONDIMRESULT(EXMAXWBAR, EX_W_HAT, STRESS_BAR, EXDISP(:)%W0, EXSTRESS, & 
					   (/INT(MAXGRID(1)+1), INT(MAXGRID(2)+1)/))

	!----- COMPUTE PUFEM APPROXIMATE SOLUTION -----
	CALL APPROXSOL(APDISP, APMOMENT, XCORDS, YCORDS, COEFF_APDISP, NDX)

	!----- COMPUTE APPROXIMATE NONDIMENSIONAL NUMERICAL RESULT -----
	CALL APNONDIMRESULT(APMAXWBAR, AP_W_HAT, APDISP(:)%W0, (/INT(MAXGRID(1)+1), INT(MAXGRID(2)+1)/))
	!----- ESTIMATE RELATIVE MAXIMUM NORM ERROR -----
	
	MAX_INDICE = (/MAXLOC(DABS(EXDISP(:)%W0)), MAXLOC(DABS(EXDISP(:)%PIX)), MAXLOC(DABS(EXDISP(:)%PIY)), &
								 MAXLOC(DABS(EXMOMENT(:)%MXX)), MAXLOC(DABS(EXMOMENT(:)%MYY)), MAXLOC(DABS(EXMOMENT(:)%MXY))/)
	
	DO I=1, NGRID
 		!----- MAXIMUM NORM ERROR -----
		ERROR_DISP(I) = DISPLACEMENT(DABS(APDISP(I)%W0 - EXDISP(I)%W0), DABS(APDISP(I)%PIX - EXDISP(I)%PIX), &
									 DABS(APDISP(I)%PIY - EXDISP(I)%PIY))
		ERROR_MOMENT(I) = MOMENT(DABS(APMOMENT(I)%MXX - EXMOMENT(I)%MXX), DABS(APMOMENT(I)%MYY - EXMOMENT(I)%MYY), &
								 DABS(APMOMENT(I)%MXY - EXMOMENT(I)%MXY))
	ENDDO

	OPEN(10, FILE = 'disp')
	OPEN(11, FILE = 'moment')
	OPEN(12, FILE = 'err_disp')
	OPEN(13, FILE = 'err_moment')
	II = 0
	DO J=1, UBOUND(YCORDS,1)
		DO I=1, UBOUND(XCORDS,1)
			II = II + 1
			WRITE(10,*) XCORDS(I), YCORDS(J), EXDISP(II), APDISP(II)
			WRITE(11,*) XCORDS(I), YCORDS(J), EXMOMENT(II), APMOMENT(II)
			WRITE(12,*) XCORDS(I), YCORDS(J), ERROR_DISP(II)
			WRITE(13,*) XCORDS(I), YCORDS(J), ERROR_MOMENT(II)
			IF (MOD(II,MAXGRID(1)+1).EQ.0) THEN
				WRITE(10,*)
				WRITE(11,*)
				WRITE(12,*)
				WRITE(13,*)
			ENDIF
		ENDDO
	ENDDO
	CLOSE(10)
	CLOSE(11)
	CLOSE(12)
	CLOSE(13)
	
	!----- INDICE WHICH INDICATE MAXIMUM NORM ERROR AT EACH ERROR
	INDICE = (/ MAXLOC(ERROR_DISP(:)%W0), MAXLOC(ERROR_DISP(:)%PIX), MAXLOC(ERROR_DISP(:)%PIY), &
			    MAXLOC(ERROR_MOMENT(:)%MXX), MAXLOC(ERROR_MOMENT(:)%MYY), MAXLOC(ERROR_MOMENT(:)%MXY) /)
	
	OPEN(15, FILE = 'result')
	WRITE(15,*) ""
	WRITE(15,*) "RELATIVE MAX. ERROR FOR DISPLACEMENTS : "
	WRITE(15,*) ""
	WRITE(15,*) "RELATIVE MAXIMUM ERROR FOR W0 : "
	WRITE(15,*) ERROR_DISP(INDICE(1))%W0 / DABS(EXDISP(MAX_INDICE(1))%W0)
	WRITE(15,*) ""
	WRITE(15,*) "RELATIVE MAXIMUM ERROR FOR PI_X : "
	WRITE(15,*) ERROR_DISP(INDICE(2))%PIX / DABS(EXDISP(MAX_INDICE(2))%PIX)
	WRITE(15,*) ""
	WRITE(15,*) "RELATIVE MAXIMUM ERROR FOR PI_Y : "
	WRITE(15,*) ERROR_DISP(INDICE(3))%PIY / DABS(EXDISP(MAX_INDICE(3))%PIY)
	WRITE(15,*) ""
	WRITE(15,*) "ERROR FOR NONDIMENSIONAL NUMERICAL RESULT : "
	WRITE(15,*) ""
	WRITE(15,*) "W BAR AT CENTER POINT"
	WRITE(15,*) "EXACT : ", EXMAXWBAR
	WRITE(15,*) "APPRO : ", APMAXWBAR
	WRITE(15,*) "RELATIVE ERROR : ", DABS((EXMAXWBAR - APMAXWBAR) / EXMAXWBAR)
	WRITE(15,*) ""
	WRITE(15,*) "MAX. W HAT"
	WRITE(15,*) "EXACT : ", EX_W_HAT
	WRITE(15,*) "APPRO : ", AP_W_HAT
	WRITE(15,*) "RELATIVE ERROR : ", DABS((EX_W_HAT - AP_W_HAT) / EX_W_HAT)
	WRITE(15,*) ""
	WRITE(15,*) "RELATIVE MAX. ERROR FOR MOMENTS : "
	WRITE(15,*) ""
	WRITE(15,*) "BENDING MOMENT MXX : "
	WRITE(15,*) ERROR_MOMENT(INDICE(4))%MXX / DABS(EXMOMENT(MAX_INDICE(4))%MXX)
	WRITE(15,*) ""
	WRITE(15,*) "BENDING MOMENT MYY : "
	WRITE(15,*) ERROR_MOMENT(INDICE(5))%MYY / DABS(EXMOMENT(MAX_INDICE(5))%MYY)
	WRITE(15,*) ""
	WRITE(15,*) "BENDING MOMENT MXY : "
	WRITE(15,*) ERROR_MOMENT(INDICE(6))%MXY / DABS(EXMOMENT(MAX_INDICE(6))%MXY)
	WRITE(15,*) ""
	CLOSE(15)
	
	OPEN(30, FILE='nondim_result')
	WRITE(30,*) "ORDER OF PU : ", GORDER
	WRITE(30,*) "ORDER OF RPP : ", IORDER
	WRITE(30,*) "SIDE OF SQUARE PLATE : ", L
	WRITE(30,*) "NUM BER OF PATCH : ", NUMPATCHES
	WRITE(30,*) "THICKNESS OF THE PLATE : ", h
	WRITE(30,*) ""
	WRITE(30,*) "SIDE-TO-THICKNESS RATIO : ", L/h
	WRITE(30,*) ""
	WRITE(30,*) "NUMBER OF TERMS USED TO FIND EXACT SOL. : ", MAXTERM,"X",MAXTERM
	WRITE(30,*) ""
	WRITE(30,*) "MAX EXACT W_BAR : ", EXMAXWBAR
	WRITE(30,*) ""
	WRITE(30,*) "MAX APPROXIMATE W_BAR", APMAXWBAR
	WRITE(30,*) ""
	WRITE(30,*) "MAXIMUM NONDIMENSIONAL DEFLECTION EX_W_HAT : ", EX_W_HAT
	WRITE(30,*) ""
	WRITE(30,*) "STRESSES OF SIMPLY SUPPORTED SQUARE PLATE"
	WRITE(30,*) "SIGMA_XX : ", STRESS_BAR%SXX
	WRITE(30,*) "SIGMA_YY : ", STRESS_BAR%SYY
	WRITE(30,*) "SIGMA_XY : ", STRESS_BAR%SXY
	WRITE(30,*) "SIGMA_XZ : ", STRESS_BAR%SXZ
	WRITE(30,*) "SIGMA_YZ : ", STRESS_BAR%SYZ
	WRITE(30,*) ""
	WRITE(30,*) "-----RELATIVE MAX. ERROR FOR NONDIMENSIONAL NUMERICAL RESULT-----"
	WRITE(30,*) "MAX W BAR : ", DABS((EXMAXWBAR - APMAXWBAR) / EXMAXWBAR)
	WRITE(30,*) "MAX. W HAT : ", DABS((EX_W_HAT - AP_W_HAT) / EX_W_HAT)
	CLOSE(30)
	
	OPEN(300, FILE='rel_max_err_disp')
	WRITE(300,*) "RELATIVE MAXIMUM ERROR FOR W0 : "
	WRITE(300,*) ERROR_DISP(INDICE(1))%W0 / DABS(EXDISP(MAX_INDICE(1))%W0)
	WRITE(300,*) ""
	WRITE(300,*) "RELATIVE MAXIMUM ERROR FOR PI_X : "
	WRITE(300,*) ERROR_DISP(INDICE(2))%PIX / DABS(EXDISP(MAX_INDICE(2))%PIX)
	WRITE(300,*) ""
	WRITE(300,*) "RELATIVE MAXIMUM ERROR FOR PI_Y : "
	WRITE(300,*) ERROR_DISP(INDICE(3))%PIY / DABS(EXDISP(MAX_INDICE(3))%PIY)
	CLOSE(300)

	DEALLOCATE(XCORDS, YCORDS, EXDISP, EXMOMENT, APDISP, ERROR_DISP, EXSTRESS, APMOMENT)

END SUBROUTINE MAXNORM

END MODULE ERRORESTIMATE

