MODULE LOADFUNCTION

    USE NEWTYPE
    USE GLBVAR

    IMPLICIT NONE

    INTERFACE LDFT
        MODULE PROCEDURE LDFT2D, LDFTVEC
    END INTERFACE LDFT

    INTERFACE UDFT
        MODULE PROCEDURE U_BD, U_BDVEC
    END INTERFACE UDFT

CONTAINS

SUBROUTINE LDFTVEC(VECVAL, VEC, N)

    INTEGER, INTENT(IN) :: N
    REAL*8, INTENT(OUT) :: VECVAL(N)
    TYPE(POINT2D), INTENT(IN) :: VEC(N)
    INTEGER :: I

    DO I=1, N
        VECVAL(I)=LDFT2D(VEC(I))
    ENDDO

END SUBROUTINE LDFTVEC

FUNCTION U_BDVEC(VEC, N)

    INTEGER, INTENT(IN) :: N
    TYPE(POINT2D), INTENT(IN) :: VEC(N)
    REAL*8 :: U_BDVEC(N)
    INTEGER :: I

    DO I=1, N
        U_BDVEC(I)=U_BD(VEC(I))
    ENDDO
END FUNCTION U_BDVEC

REAL*8 FUNCTION LDFT2D(PT2D)

    TYPE(POINT2D), INTENT(IN) :: PT2D
    REAL*8 :: X, Y

    X=PT2D%X
    Y=PT2D%Y
    
	LDFT2D=LOAD_Q
	
END FUNCTION LDFT2D

REAL*8 FUNCTION U_BD(PT2D)

    TYPE(POINT2D), INTENT(IN) :: PT2D
    REAL*8 :: X,Y

    X=PT2D%X
    Y=PT2D%Y

	IF (PROBLEM.EQ.0) THEN
!		TRUE SOLUTION
!		U_BD=(X**2-1.0D0)*(Y**2-Y)
		U_BD=0.0D0
	ELSEIF (PROBLEM.EQ.1) THEN
		U_BD=0.0D0
	ELSEIF (PROBLEM.EQ.2) THEN
		U_BD=0.0D0
	ELSEIF (PROBLEM.EQ.3) THEN
		U_BD=0.0D0
	ENDIF
	
END FUNCTION U_BD

END MODULE LOADFUNCTION
